"""Add all new features: password_reset, first_login, and permission system

Revision ID: 46624e79df79
Revises: 35349ae37f5a
Create Date: 2026-02-23 20:34:11.303548

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46624e79df79'
down_revision = '35349ae37f5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_name')
    )
    op.create_table('user_module_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_name', sa.String(length=64), nullable=False),
    sa.Column('can_create', sa.Boolean(), nullable=True),
    sa.Column('can_read', sa.Boolean(), nullable=True),
    sa.Column('can_update', sa.Boolean(), nullable=True),
    sa.Column('can_delete', sa.Boolean(), nullable=True),
    sa.Column('granted_by_id', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['granted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'module_name', name='uq_user_module')
    )

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    has_password_reset_tokens = 'password_reset_tokens' in inspector.get_table_names()

    if not has_password_reset_tokens:
        # Some environments created the base schema without this table.
        op.create_table(
            'password_reset_tokens',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('user_id', sa.Integer(), nullable=False),
            sa.Column('token', sa.String(length=255), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('expires_at', sa.DateTime(), nullable=False),
            sa.Column('used', sa.Boolean(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('token'),
        )
        op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
        op.create_index('idx_password_reset_tokens_token', 'password_reset_tokens', ['token'], unique=True)
    else:
        # Fresh databases may not have these legacy index names; make this step idempotent.
        op.execute("DROP INDEX IF EXISTS idx_password_reset_tokens_token")
        op.execute("DROP INDEX IF EXISTS idx_password_reset_tokens_user_id")

        with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('password_reset_token_user_id_fkey'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # The initial migration in this repo creates a minimal users table. On a fresh DB,
    # these newer columns do not exist yet, so we add them before altering.
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    user_cols = {c["name"] for c in inspector.get_columns("users")}

    if "status" not in user_cols:
        op.add_column(
            "users",
            sa.Column("status", sa.String(length=32), nullable=False, server_default=sa.text("'Ativo'")),
        )
    if "permissions" not in user_cols:
        op.add_column("users", sa.Column("permissions", sa.JSON(), nullable=True))
    if "first_login" not in user_cols:
        op.add_column(
            "users",
            sa.Column("first_login", sa.Boolean(), nullable=False, server_default=sa.text("true")),
        )
    if "password_reset_required" not in user_cols:
        op.add_column(
            "users",
            sa.Column("password_reset_required", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        )
    if "key" not in user_cols:
        op.add_column("users", sa.Column("key", sa.String(length=64), nullable=True))

    # Re-introspect after potential adds.
    user_cols = {c["name"] for c in inspector.get_columns("users")}

    with op.batch_alter_table("users", schema=None) as batch_op:
        if "status" in user_cols:
            batch_op.alter_column(
                "status",
                existing_type=sa.VARCHAR(length=32),
                nullable=False,
                existing_server_default=sa.text("'Ativo'::character varying"),
            )
        # Some DBs may have JSONB; if not present, we already created JSON above.
        if "permissions" in user_cols:
            batch_op.alter_column(
                "permissions",
                type_=sa.JSON(),
                existing_nullable=True,
            )
        if "first_login" in user_cols:
            batch_op.alter_column(
                "first_login",
                existing_type=sa.BOOLEAN(),
                nullable=False,
                existing_server_default=sa.text("true"),
            )
        if "password_reset_required" in user_cols:
            batch_op.alter_column(
                "password_reset_required",
                existing_type=sa.BOOLEAN(),
                nullable=False,
                existing_server_default=sa.text("false"),
            )
        if "key" in user_cols:
            batch_op.create_index(batch_op.f("ix_users_key"), ["key"], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_key'))
        batch_op.alter_column('password_reset_required',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('permissions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'Ativo'::character varying"))

    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('password_reset_token_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_password_reset_tokens_token'), ['token'], unique=False)

    op.drop_table('user_module_permissions')
    op.drop_table('module_permissions')
    # ### end Alembic commands ###
