"""Add CASCADE to remaining project foreign keys

Revision ID: b9538565cb22
Revises: h1i2j3k4l5m6
Create Date: 2026-03-07 11:55:20.878723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9538565cb22'
down_revision = 'h1i2j3k4l5m6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('communication_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('communication_plans_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_charters', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('project_charters_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('project_closures', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('project_closures_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('reports_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('requirements_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('scope_changes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('scope_changes_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('stakeholders_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('tasks_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('time_entries_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('wbs_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('wbs_items_project_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'projects', ['project_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wbs_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('wbs_items_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('time_entries', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('time_entries_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('tasks_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('stakeholders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('stakeholders_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('scope_changes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('scope_changes_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('requirements_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('reports_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('project_closures', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('project_closures_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('project_charters', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('project_charters_project_id_fkey'), 'projects', ['project_id'], ['id'])

    with op.batch_alter_table('communication_plans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('communication_plans_project_id_fkey'), 'projects', ['project_id'], ['id'])

    # ### end Alembic commands ###
