"""Add enhanced fields to projects table

Revision ID: eb6013d3c3e0
Revises: 46624e79df79
Create Date: 2026-02-23 20:59:11.109949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6013d3c3e0'
down_revision = '46624e79df79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('budget', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('actual_cost', sa.Numeric(precision=15, scale=2), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('priority', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('client_name', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('client_name')
        batch_op.drop_column('location')
        batch_op.drop_column('priority')
        batch_op.drop_column('category')
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('budget')

    # ### end Alembic commands ###
